# Generated by Django 4.0.4 on 2022-08-18 04:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('area', models.FloatField()),
                ('area_unit', models.CharField(choices=[('BG', 'Bigha'), ('KT', 'Kattha'), ('RO', 'Ropani'), ('AN', 'Aana'), ('SF', 'SquareFeet'), ('SM', 'SquareMile')], default='AN', max_length=2)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('land_image', models.ImageField(upload_to='land_images/%Y/%m/%d/')),
                ('landownership_image', models.ImageField(upload_to='ownership_images/%Y/%m/%d/')),
                ('landownership_image_optional', models.ImageField(blank=True, upload_to='ownership_images/%Y/%m/%d/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('is_house_or_apartment', models.BooleanField(default=False)),
                ('total_no_of_rooms', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('no_of_bedroom', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('no_of_washroom', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('house_image', models.ImageField(blank=True, default=None, upload_to='house_images/%Y/%m/%d/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, default=None, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
