# Generated by Django 4.0.4 on 2022-04-20 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('area', models.FloatField()),
                ('area_unit', models.CharField(choices=[('BG', 'Bigha'), ('KT', 'Kattha'), ('RO', 'Ropani'), ('AN', 'Aana'), ('SF', 'SquareFeet'), ('SM', 'SquareMile')], default='AN', max_length=2)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('image', models.ImageField(upload_to='land_images/%Y/%m/%d/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
