# Generated by Django 4.0.4 on 2022-04-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='price',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
    ]
