# Generated by Django 4.0.4 on 2022-04-22 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_land_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RenameField(
            model_name='land',
            old_name='image',
            new_name='land_image',
        ),
        migrations.AddField(
            model_name='land',
            name='landownership_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ownership_images/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='landownership_image_optional',
            field=models.ImageField(blank=True, upload_to='ownership_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='land',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
