# Generated by Django 4.0.4 on 2022-04-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_land_house_image_land_is_house_land_no_of_bedroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='is_house',
            new_name='is_house_or_apartment',
        ),
    ]
